apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-moving

resources:
  - ../../base

labels:
  - pairs:
      environment: staging
    includeSelectors: true

images:
  - name: ghcr.io/london-bridge/money-moving/payment
    newTag: "stg-latest"
  - name: ghcr.io/london-bridge/money-moving/manager
    newTag: "stg-latest"
  - name: ghcr.io/london-bridge/money-moving/seamless
    newTag: "stg-latest"
  - name: ghcr.io/london-bridge/money-moving/seamless-pix
    newTag: "stg-latest"
  - name: ghcr.io/london-bridge/money-moving/ledger
    newTag: "main-0a27cd14"
  - name: ghcr.io/london-bridge/money-moving/ledger-backoffice
    newTag: "main-4b932c5d"

patches:
  - target:
      kind: ConfigMap
      name: money-moving-shared-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: staging
      - op: replace
        path: /data/LOG_LEVEL
        value: info
  - target:
      kind: ExternalSecret
      name: money-moving-shared-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /money-moving/staging/manual-secrets
  - target:
      kind: Deployment
      name: payment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: manager
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: seamless
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: seamless-pix
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: ledger
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
  - target:
      kind: Deployment
      name: ledger-backoffice
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
