apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: http://redpanda.stg-infra.svc.cluster.local:8081
            - name: KAFKA_BROKERS_URL
              value: redpanda.stg-infra.svc.cluster.local:9092
