apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-moving

resources:
  - ../../base

labels:
  - pairs:
      environment: qa
    includeSelectors: true

images:
  - name: ghcr.io/london-bridge/money-moving/payment
    newTag: "186498e8"
  - name: ghcr.io/london-bridge/money-moving/manager
    newTag: "186498e8"
  - name: ghcr.io/london-bridge/money-moving/seamless
    newTag: "186498e8"
  - name: ghcr.io/london-bridge/money-moving/seamless-pix
    newTag: "186498e8"
  - name: ghcr.io/london-bridge/money-moving/ledger
    newTag: "186498e8"
  - name: ghcr.io/london-bridge/money-moving/ledger-backoffice
    newTag: "186498e8"

patches:
  - target:
      kind: ConfigMap
      name: money-moving-shared-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: qa
      - op: replace
        path: /data/LOG_LEVEL
        value: info
  - target:
      kind: ExternalSecret
      name: shared-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /money-moving/qa/manual-secrets
  - target:
      kind: ExternalSecret
      name: ledger-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /money-moving/qa/manual-secrets
  - target:
      kind: Deployment
      name: payment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: manager
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: seamless
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: seamless-pix
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: ledger
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 300Mi
  - target:
      kind: Deployment
      name: ledger-backoffice
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
