apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-moving

resources:
  - ../../base

labels:
  - pairs:
      environment: qa
    includeSelectors: true

images:
  - name: ghcr.io/london-bridge/money-moving/ledger
    newTag: qa-latest

patches:
  - target:
      kind: ConfigMap
      name: money-moving-shared-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: qa
      - op: replace
        path: /data/LOG_LEVEL
        value: info
  - target:
      kind: ExternalSecret
      name: money-moving-shared-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /money-moving/qa/manual-secrets
  - target:
      kind: Deployment
      name: ledger
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 300Mi
