apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: money-moving
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJiRzl1Wkc5dUxXSnlhV1JuWlRwbmFIQmZZV05qWlhOelgyTnZiblJsYm5SZmRHOXJaVzVmYUdWeVpRPT0ifX19
