apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-moving

resources:
  - shared-configmap.yaml
  - ledger-configmap.yaml
  - ledger-v2-configmap.yaml
  - shared-external-secret.yaml
  - ghcr-external-secret.yaml
  - ledger-external-secret.yaml
  - payment-deployment.yaml
  - payment-service.yaml
  - manager-deployment.yaml
  - manager-service.yaml
  - seamless-deployment.yaml
  - seamless-service.yaml
  - seamless-pix-deployment.yaml
  - seamless-pix-service.yaml
  - ledger-deployment.yaml
  - ledger-service.yaml
  - ledger-v2-deployment.yaml
  - ledger-v2-service.yaml
  - ledger-backoffice-deployment.yaml
  - ledger-backoffice-service.yaml
  - ledger-backoffice-ingress.yaml
  - rds-ca-cert-configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: money-moving
