apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
  namespace: money-moving
  labels:
    app: ledger
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
        version: v2
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ledger
          image: ghcr.io/london-bridge/money-moving/ledger:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: GRPC_PORT
              value: "50051"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: money-moving-shared-config
                  key: LOG_LEVEL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: money-moving-shared-config
                  key: ENVIRONMENT
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: money-moving-shared-config
                  key: SERVICE_NAME
          envFrom:
            - secretRef:
                name: money-moving-shared-secret
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
