apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-v2-config
  labels:
    app.kubernetes.io/name: ledger-v2
    app.kubernetes.io/part-of: money-moving
data:
  # PostgreSQL Configuration (Read Model + Metadata)
  DB_HOST: "postgresql.development.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "ledger"
  DB_USER: "ledger"
  DB_SSLMODE: "disable"

  # TigerBeetle Configuration (Write Model - distributed ledger)
  TIGERBEETLE_ADDRESSES: "10.0.4.216:3000"
  TIGERBEETLE_CLUSTER_ID: "0"

  # Pulsar Configuration (Event Streaming)
  PULSAR_URL: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"

  # gRPC Configuration
  GRPC_PORT: "50051"

  # Application Configuration
  LOG_LEVEL: "info"
  ENVIRONMENT: "dev"
  SERVICE_NAME: "ledger-v2"
