---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: money-moving-shared-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /money-moving/dev/manual-secrets
