apiVersion: v1
kind: ConfigMap
metadata:
  name: money-moving-shared-config
  namespace: money-moving
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "dev"
  SERVICE_NAME: "money-moving"
  STORAGE_DRIVER: "postgres"

  # Redis Configuration
  REDIS_URL: "redis.qa-infra.svc.cluster.local:6379"

  # PostgreSQL Configuration (ledger-v2)
  DB_HOST: "postgresql.development.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "dev"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_SSLMODE: "disable"  # Dev usa disable, staging/prod usa require

  # TigerBeetle Configuration (ledger-v2)
  TIGERBEETLE_ADDRESSES: "10.0.4.216:3000"
  TIGERBEETLE_CLUSTER_ID: "0"

  # Pulsar Configuration (ledger-v2)
  PULSAR_URL: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
