apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-moving

resources:
  - ../../base
  - shared-external-secret.yaml

labels:
  - pairs:
      environment: dev
    includeSelectors: true

images:
  - name: ghcr.io/london-bridge/money-moving/ledger
    newTag: main-1cad2e17
  - name: ghcr.io/london-bridge/money-moving/ledger-backoffice
    newTag: main-fa0c38ed

patches:
  - target:
      kind: ConfigMap
      name: money-moving-shared-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: dev
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
  - target:
      kind: ExternalSecret
      name: money-moving-shared-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /money-moving/dev/manual-secrets
  - target:
      kind: Deployment
      name: ledger
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 200Mi
  - target:
      kind: Deployment
      name: ledger-backoffice
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
