apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: money-moving

resources:
  - ../../base
  - shared-external-secret.yaml

labels:
  - pairs:
      environment: dev
    includeSelectors: true

images:
  - name: ghcr.io/london-bridge/money-moving/payment
    newTag: "620da5f6"
  - name: ghcr.io/london-bridge/money-moving/manager
    newTag: "186498e8"
  - name: ghcr.io/london-bridge/money-moving/seamless
    newTag: latest
  - name: ghcr.io/london-bridge/money-moving/seamless-pix
    newTag: latest
  - name: ghcr.io/london-bridge/money-moving/ledger
    newTag: "186498e8"
  - name: ghcr.io/london-bridge/money-moving/ledger-backoffice
    newTag: "fbcb44ec"

patches:
  - target:
      kind: ConfigMap
      name: money-moving-shared-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: dev
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
  - target:
      kind: ExternalSecret
      name: money-moving-shared-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /money-moving/dev/manual-secrets
  - target:
      kind: ExternalSecret
      name: ledger-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /money-moving/dev/manual-secrets
      - op: replace
        path: /spec/refreshInterval
        value: 1h
  - target:
      kind: Deployment
      name: payment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
  - target:
      kind: Deployment
      name: manager
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
  - target:
      kind: Deployment
      name: seamless
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
  - target:
      kind: Deployment
      name: seamless-pix
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
  - target:
      kind: Deployment
      name: ledger
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 200Mi
  - target:
      kind: Deployment
      name: ledger-backoffice
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
